baseURL = "https://liuyiyueyue.github.io/"
languageCode = "en-us"
title = "Yiyue (Lily) Liu"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true

[params.profileMode]
  enabled = true
  title = "Welcome to my blog!"
  subtitle = "ML and systems notes"

