baseURL = "https://liuyiyueyue.github.io/"
languageCode = "en-us"
title = "Yiyue (Lily) Liu"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true

[params.homeInfoParams]
  Title = "This is my personal technical blog."
  Content = """
- Large-scale training and inference
- Systems & concurrency
- Kernel-level concepts
- Distributed systems
- Software engineering
"""

[params.profileMode]
  enabled = false

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Engineering"
    url = "/engineering/"
    weight = 2
